# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('P', 'In-progress'), ('C', 'Completed')], default='P', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'To-do item',
                'verbose_name_plural': 'To-do items',
            },
        ),
    ]
