# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'In-progress'), ('C', 'Completed')], default='P', max_length=1),
        ),
    ]
