# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181018_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='datetime',
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
